# Generated by Django 3.2 on 2021-07-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniquesb_app', '0002_rendezvous_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
