# Generated by Django 3.2 on 2021-07-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniquesb_app', '0003_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='Null', max_length=50, null=True, unique=True),
        ),
    ]
