# Generated by Django 3.2 on 2021-07-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniquesb_app', '0006_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docteur',
            name='dateNaissance',
            field=models.CharField(max_length=15, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='docteur',
            name='nomDocteur',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom'),
        ),
        migrations.RemoveField(
            model_name='docteur',
            name='post',
        ),
        migrations.AddField(
            model_name='docteur',
            name='post',
            field=models.ManyToManyField(to='cliniquesb_app.Post'),
        ),
        migrations.AlterField(
            model_name='docteur',
            name='prenomDocteur',
            field=models.CharField(max_length=50, null=True, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='docteur',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
    ]
