# Generated by Django 3.2 on 2021-07-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniquesb_app', '0008_alter_listdocteur_nomdocteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='docteur',
            name='email',
            field=models.EmailField(blank=True, max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='docteur',
            name='sexe',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='docteur',
            name='tel',
            field=models.CharField(max_length=20, unique=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='post',
            name='nomPost',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom du post'),
        ),
    ]
