# Generated by Django 3.2 on 2021-07-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniquesb_app', '0010_auto_20210709_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='messages',
        ),
        migrations.AlterField(
            model_name='docteur',
            name='post',
            field=models.ManyToManyField(related_name='posts', to='cliniquesb_app.Post'),
        ),
    ]
