# Generated by Django 3.2 on 2021-07-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniquesb_app', '0011_auto_20210709_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statutRdv',
            field=models.CharField(blank=True, choices=[('Confirmer', 'CONFIRMER'), ('Non Confirmer', 'NON CONFIRMER'), ('Annuler', 'Annuler')], default='En traitement', max_length=14, null=True, verbose_name='Statut du rendez-vous'),
        ),
    ]
